// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjzqjoaqorudgtalthnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqenFqb2Fxb3J1ZGd0YWx0aG5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMDQ2MDMsImV4cCI6MjA2NzY4MDYwM30.qznFuAlemI_CDeTU4SUvBAgZM6QtIana8sIKtuzjQis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});